@baseUrl = http://localhost:3000

###Obtener todos los mantenimientos
GET {{baseUrl}}/maintenance

### Mantenimientos por servicio
GET {{baseUrl}}/maintenance/service/srv-002

### Mantenimientos por cadena
GET {{baseUrl}}/maintenance?cadena=hola

### Crear mantenimiento
POST {{baseUrl}}/maintenance
Content-Type: application/json

{
  "_id": "mnt-005",
  "serviceId": "srv-005",
  "titulo": "Mantenimiento programado de base de datos",
  "descripcion": "Actualización de índices",
  "estado": "Programado",
  "cadena": "hola",
  "restaurante": "KFC Mall del Sol",
  "fechaInicio": "2025-12-24T01:00:00Z",
  "fechaFin": "2025-12-24T02:00:00Z"
}

### Cambiar estado
PATCH http://localhost:3000/maintenance/mnt-001
Content-Type: application/json

{
  "estado": "En progreso"
}
